services:

    php_qa:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php_qa
        volumes:
            - ./:/var/www
        networks:
            - qa_net
        environment:
            PHP_IDE_CONFIG: serverName=Docker # For Xdebug
        restart: unless-stopped

    nginx_qa:
        image: nginx
        container_name: nginx_qa
        volumes:
            - ./public:/var/www/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php_qa
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.nginx_qa.tls=true
            - traefik.http.routers.nginx_qa.rule=Host(`${NGINX_HOST}`) || Host(`${NGINX_HOST_WWW}`)
            - traefik.http.routers.nginx_qa.entrypoints=websecure
            - traefik.http.services.nginx_qa.loadbalancer.server.port=80
            # redirect www to non-www
            - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
            - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
            - traefik.http.routers.nginx_qa.middlewares=mywwwredirect
        networks:
            - qa_net

    mariadbapi:
        image: mariadb:latest
        container_name: mariadbapi
        restart: always
        ports:
            - 3307:3306
        environment:
            MARIADB_ROOT_PASSWORD: $DB_PASSWORD
            MARIADB_DATABASE: $DB_DATABASE
            MARIADB_USER: $DB_USERNAME
            MARIADB_PASSWORD: $DB_PASSWORD
            APP_DB_HOST: $ADMINER_HOST
            APP_DB_USER: $DB_USERNAME
            APP_DB_PASSWD: $DB_PASSWORD
        volumes:
            - ./dbdata:/var/lib/mysql
        labels:
            - traefik.enable=true
            - traefik.tcp.routers.mariadbapi.rule=HostSNI(`*`)
            - traefik.tcp.services.mariadbapi.loadbalancer.server.port=3306
            - traefik.tcp.routers.mariadbapi.entrypoints=mariadbapi
        networks:
            - qa_net

    adminerapi:
        image: adminer
        container_name: adminerapi
        restart: always
        labels:
            - traefik.enable=true
            - traefik.http.routers.adminerapi.tls=true
            - traefik.http.routers.adminerapi.rule=Host(`${ADMINER_HOST}`)
            - traefik.http.routers.adminerapi.entrypoints=websecure
        depends_on:
            - mariadbapi
        networks:
            - qa_net

networks:
    qa_net:
        name: "proxy"
        external: true

